# Generated by Django 3.1 on 2020-08-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Announce_msg', models.TextField()),
                ('Is_pinned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, upload_to='Media')),
                ('Announcement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
            ],
        ),
    ]
