# Generated by Django 3.1 on 2020-08-18 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement_file',
            name='Announcement_id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='DateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announcement',
            name='File_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement_file'),
        ),
        migrations.AlterField(
            model_name='announcement_file',
            name='File',
            field=models.FileField(blank=True, upload_to='announcement/Media'),
        ),
    ]
