# Generated by Django 3.1 on 2020-08-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Topic', models.CharField(max_length=100)),
                ('Event_Startdate', models.DateField()),
                ('Event_Enddate', models.DateField()),
                ('Event_Time', models.TimeField()),
                ('Event_Msg', models.TextField()),
                ('Event_File', models.FileField(upload_to='')),
            ],
        ),
    ]
