# Generated by Django 3.1 on 2020-08-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.TextField()),
                ('Event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.events')),
            ],
        ),
    ]
