# Generated by Django 3.1 on 2020-08-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventreply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
