# Generated by Django 3.1 on 2020-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200824_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='media/user-images/'),
        ),
    ]
